### ISSUE TITLE
TypeError: Not enough arguments to Worker.postMessage

### ISSUE THREAD

**Issue by Majkl578** [Venefilyn/edbm#2]
main.min.js:2:91

Firefox 39.0a2

**Comment by Venefilyn** [comment]
Yes, this has something to do with the Web Worker. It currently doesn't work and yields no benefit as it doesn't work, it's something I'll look into more to see if I can fix it with inline-code

**Comment by Venefilyn** [comment]
Web worker now removed due to optimisations
